#!/usr/bin/bash
# Run argument sent to this script with custom command
customcommands=".config/dmenu/customcommands"

line=$(grep "^$@:.*$" "$customcommands")
line=${line#"$@:"}
if [[ -n "$line" ]]; then
	eval $line
else
	eval $@
fi
