#!/bin/bash 
# This script returns results of 'locate' command in a convenient dmenu form

DMENU_CONFIG="$HOME/.config/dmenu/config"

# Load config
if [[ -f "$DMENU_CONFIG" ]]; then 
    source "$DMENU_CONFIG"
else
    DMENU() { dmenu "$@"; }
fi

# Request name and print results
request=( $(echo "" \
	| DMENU -i -p "file pathname contains (regexp permitted):" ) )
	
locate --regex "${request}" \
	| DMENU -p "select file to copy path to clipboard" -i -l 20 \
	| sed '/^\//!{s/^/\//}' \
	| tr -d "\n" \
	| xclip -selection c && notify-send "path copied to clipboard"
